# Generated by Django 3.1.3 on 2021-10-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211002_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classrooms')),
            ],
        ),
    ]
